// client/src/components/chatbot/CareerRoadmapVisualization.jsx
import React, { useCallback, useMemo } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Box,
  Typography,
  Chip,
  IconButton,
  Paper,
  useTheme,
  useMediaQuery
} from '@mui/material';
import {
  Close,
  Timeline,
  EmojiEvents,
  School,
  WorkOutline,
  Star,
  TrendingUp
} from '@mui/icons-material';

// Mock React Flow implementation since we can't install it yet
const MockReactFlow = ({ nodes, edges }) => {
  const theme = useTheme();
  
  return (
    <Box sx={{ 
      width: '100%', 
      height: 400,
      bgcolor: theme.palette.background.default,
      border: `1px solid ${theme.palette.divider}`,
      borderRadius: 2,
      p: 2,
      overflow: 'auto'
    }}>
      {nodes.map((node, index) => (
        <Paper
          key={node.id}
          sx={{
            p: 2,
            mb: 2,
            bgcolor: node.type === 'start' ? theme.palette.success.light :
                     node.type === 'milestone' ? theme.palette.primary.light :
                     node.type === 'professional' ? theme.palette.secondary.light :
                     theme.palette.info.light,
            color: 'white',
            position: 'relative',
            '&:after': index < nodes.length - 1 ? {
              content: '""',
              position: 'absolute',
              bottom: -16,
              left: '50%',
              width: 0,
              height: 0,
              borderLeft: '8px solid transparent',
              borderRight: '8px solid transparent',
              borderTop: `8px solid ${theme.palette.primary.main}`,
              transform: 'translateX(-50%)'
            } : {}
          }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
            {node.icon}
            <Typography variant="h6" component="div">
              {node.data.label}
            </Typography>
          </Box>
          <Typography variant="body2" sx={{ opacity: 0.9 }}>
            {node.data.description}
          </Typography>
          {node.data.timeframe && (
            <Chip 
              label={node.data.timeframe}
              size="small"
              sx={{ mt: 1, bgcolor: 'rgba(255,255,255,0.2)' }}
            />
          )}
          {node.data.requirements && (
            <Box sx={{ mt: 1 }}>
              <Typography variant="caption" sx={{ fontWeight: 'bold' }}>
                Requirements:
              </Typography>
              <Typography variant="caption" sx={{ display: 'block', mt: 0.5 }}>
                {node.data.requirements.join(', ')}
              </Typography>
            </Box>
          )}
        </Paper>
      ))}
    </Box>
  );
};

const CareerRoadmapVisualization = ({ open, onClose, careerData }) => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  const nodes = useMemo(() => {
    if (!careerData || !careerData.stages) return [];

    return careerData.stages.map((stage, index) => ({
      id: `stage-${index}`,
      type: stage.type || 'default',
      data: {
        label: stage.title,
        description: stage.description,
        timeframe: stage.timeframe,
        requirements: stage.requirements || []
      },
      icon: stage.type === 'start' ? <School /> :
            stage.type === 'milestone' ? <EmojiEvents /> :
            stage.type === 'professional' ? <WorkOutline /> :
            <Star />
    }));
  }, [careerData]);

  const edges = useMemo(() => {
    if (!nodes.length) return [];
    
    return nodes.slice(0, -1).map((_, index) => ({
      id: `edge-${index}`,
      source: `stage-${index}`,
      target: `stage-${index + 1}`,
      type: 'smoothstep',
    }));
  }, [nodes]);

  const downloadRoadmap = () => {
    // Create downloadable content
    const content = `
SPORTS CAREER ROADMAP - ${careerData?.sport?.toUpperCase() || 'ATHLETICS'}
Generated by VIKSORASPORTS Career Guidance

${nodes.map((node, index) => `
${index + 1}. ${node.data.label}
   ${node.data.description}
   ${node.data.timeframe ? `Timeline: ${node.data.timeframe}` : ''}
   ${node.data.requirements?.length ? `Requirements: ${node.data.requirements.join(', ')}` : ''}
`).join('\n')}

Official Sources: ${careerData?.sources?.join(', ') || 'Various Sports Federations'}
Generated on: ${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${careerData?.sport || 'sports'}_career_roadmap.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      fullScreen={isMobile}
      PaperProps={{
        sx: {
          bgcolor: theme.palette.background.default,
          minHeight: isMobile ? '100vh' : 500
        }
      }}
    >
      <DialogTitle sx={{ 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'space-between',
        bgcolor: theme.palette.primary.main,
        color: 'white'
      }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Timeline />
          <Box>
            <Typography variant="h6">
              {careerData?.sport || 'Sports'} Career Roadmap
            </Typography>
            <Typography variant="caption" sx={{ opacity: 0.8 }}>
              Interactive Career Path Visualization
            </Typography>
          </Box>
        </Box>
        <IconButton onClick={onClose} sx={{ color: 'white' }}>
          <Close />
        </IconButton>
      </DialogTitle>

      <DialogContent sx={{ p: 0 }}>
        {/* Career Overview */}
        <Paper sx={{ m: 2, p: 2, bgcolor: theme.palette.info.light, color: 'white' }}>
          <Typography variant="h6" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
            <TrendingUp />
            Career Overview
          </Typography>
          <Typography variant="body2">
            {careerData?.overview || 'This roadmap shows the typical progression path for athletes in this sport, from beginner level to professional career opportunities.'}
          </Typography>
          {careerData?.estimatedDuration && (
            <Chip 
              label={`Total Duration: ${careerData.estimatedDuration}`}
              sx={{ mt: 1, bgcolor: 'rgba(255,255,255,0.2)' }}
            />
          )}
        </Paper>

        {/* Roadmap Visualization */}
        <Box sx={{ p: 2 }}>
          <MockReactFlow nodes={nodes} edges={edges} />
        </Box>

        {/* Additional Resources */}
        {careerData?.resources && (
          <Paper sx={{ m: 2, p: 2 }}>
            <Typography variant="h6" sx={{ mb: 1 }}>
              Additional Resources
            </Typography>
            {careerData.resources.map((resource, index) => (
              <Chip
                key={index}
                label={resource}
                variant="outlined"
                size="small"
                sx={{ mr: 1, mb: 1 }}
              />
            ))}
          </Paper>
        )}

        {/* Official Sources */}
        {careerData?.sources && (
          <Paper sx={{ m: 2, p: 2, bgcolor: theme.palette.success.light, color: 'white' }}>
            <Typography variant="h6" sx={{ mb: 1 }}>
              ✅ Official Sources
            </Typography>
            <Typography variant="body2">
              Information sourced from: {careerData.sources.join(', ')}
            </Typography>
          </Paper>
        )}
      </DialogContent>

      <DialogActions sx={{ p: 2, gap: 1 }}>
        <Button onClick={downloadRoadmap} variant="outlined" startIcon={<Timeline />}>
          Download Roadmap
        </Button>
        <Button onClick={onClose} variant="contained">
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default CareerRoadmapVisualization;